const express=require("express"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),{v4:uuidv4}=require("uuid"),db=require("../db/database"),{authenticate:authenticate}=require("../middleware/auth"),router=express.Router(),PRESIDENT_PHONE="+22890496651",SECRET=process.env.JWT_SECRET||"change_me_in_production",SALT_ROUNDS=10,SIGNUP_FEE=2e3,PRESIDENT_BASE_SHARE=750;function normalizePhone(e){return String(e||"").replace(/\D/g,"")}function normalizeReferralCode(e){return String(e||"").trim().toUpperCase().replace(/\s+/g,"").replace(/^HWT[-_]?/,"")}function findPresident(){return db.prepare("SELECT * FROM users").all().find(e=>normalizePhone(e.phone)===normalizePhone("+22890496651"))||null}function findReferrer(e){const r=normalizeReferralCode(e);if(!r)return null;return db.prepare("SELECT * FROM users").all().find(e=>normalizeReferralCode(e.referral_code)===r)||null}function makeReferralCode(){const e="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let r="";for(let s=0;s<6;s++)r+=e[Math.floor(32*Math.random())];return"HWT-"+r}function toUser(e){return e?{id:e.id,name:e.name,surname:e.surname,phone:e.phone,profession:e.profession,neighborhood:e.neighborhood,referralCode:e.referral_code,referrerId:e.referrer_id,grade:e.grade,bio:e.bio,skills:JSON.parse(e.skills||"[]"),avatar:e.avatar,balance:Number(e.balance||0),totalEarnings:Number(e.total_earnings||0),networkCount:Number(e.network_count||0),branches:JSON.parse(e.branches||"{}"),inviteLimit:e.invite_limit,isBanned:!!e.is_banned,isSuspended:!!e.is_suspended,tutorialSeen:!!e.tutorial_seen,joinedAt:e.created_at}:null}router.post("/register",(e,r)=>{const{name:s,surname:n,phone:o,password:t,profession:i,neighborhood:a,referrerCode:u}=e.body;if(!(s&&n&&o&&t))return r.status(400).json({success:!1,message:"Nom, prénom, téléphone et mot de passe obligatoires"});if(t.length<6)return r.status(400).json({success:!1,message:"Le mot de passe doit faire au moins 6 caractères"});if(o.replace(/\D/g,"").length<8)return r.status(400).json({success:!1,message:"Numéro de téléphone invalide"});const d=normalizePhone(o);if(db.prepare("SELECT id FROM users").all().find(e=>normalizePhone(e.phone)===d))return r.status(409).json({success:!1,message:"Ce numéro est déjà utilisé. Connectez-vous plutôt."});let p=null,c=null;if(u&&String(u).trim()){if(p=findReferrer(u),!p)return r.status(400).json({success:!1,message:"Code de parrainage invalide"});c=p.id}const l=uuidv4(),m=makeReferralCode(),E=bcrypt.hashSync(t,10),f=o.trim(),b=normalizePhone(f)===normalizePhone("+22890496651")?"president":"membre";db.prepare("
    INSERT INTO users (id, name, surname, phone, profession, neighborhood,
      referral_code, referrer_id, grade, password_hash)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  ").run(l,s.trim(),n.trim(),f,(i||"").trim(),(a||"").trim(),m,c,b,E);const h=findPresident(),g=new Map,S=(e,r)=>{e&&r>0&&g.set(e,(g.get(e)||0)+r)};db.transaction(()=>{if(0===db.prepare("INSERT OR IGNORE INTO membership_events (id, user_id, amount, referrer_id) VALUES (?, ?, ?, ?)").run(uuidv4(),l,2e3,c).changes)return!1;if(c){let e=2e3;h&&(S(h.id,750),e-=750);let r=p,s=500;const n=new Set;for(;r&&e>0&&!n.has(r.id);){n.add(r.id);const o=Math.min(s,e);S(r.id,o),e-=o,s=Math.max(1,Math.floor(s/3)),r=r.referrer_id?db.prepare("SELECT * FROM users WHERE id = ?").get(r.referrer_id):null}h&&e>0&&S(h.id,e)}else h&&S(h.id,2e3);for(const[e,r]of g)db.prepare("UPDATE users SET balance = balance + ?, total_earnings = total_earnings + ? WHERE id = ?").run(r,r,e),db.prepare("INSERT INTO notifications (id, user_id, type, title, body) VALUES (?, ?, 'mlm', ?, ?)").run(uuidv4(),e,"Commission reçue",`Votre commission d'adhésion de ${r} FCFA a été créditée.`);return c&&db.prepare("UPDATE users SET network_count = network_count + 1 WHERE id = ?").run(c),!0})();const C=toUser(db.prepare("SELECT * FROM users WHERE id = ?").get(l)),R=jwt.sign({id:C.id},SECRET,{expiresIn:"30d"});db.prepare(`INSERT INTO notifications (id, user_id, type, title, body)
    VALUES (?, ?, 'system', 'Bienvenue sur Hawtrix !',
    'Votre compte a été créé avec succès. Code parrainage : ${m}')`).run(uuidv4(),l),r.status(201).json({success:!0,message:"Compte créé avec succès",user:C,token:R})}),router.post("/login",(e,r)=>{const{phone:s,password:n}=e.body;if(!s||!n)return r.status(400).json({success:!1,message:"Téléphone et mot de passe obligatoires"});let o=db.prepare("SELECT * FROM users").all().find(e=>normalizePhone(e.phone)===normalizePhone(s));if(!o)return r.status(401).json({success:!1,message:"Numéro introuvable. Créez un compte d'abord."});if(!bcrypt.compareSync(n,o.password_hash))return r.status(401).json({success:!1,message:"Mot de passe incorrect"});if(normalizePhone(s)===normalizePhone("+22890496651")&&"president"!==o.grade&&(db.prepare("UPDATE users SET grade = 'president' WHERE id = ?").run(o.id),o=db.prepare("SELECT * FROM users WHERE id = ?").get(o.id)),o.is_banned)return r.status(403).json({success:!1,message:"Ce compte a été banni par l'administrateur"});const t=toUser(o),i=jwt.sign({id:t.id},SECRET,{expiresIn:"30d"});r.json({success:!0,message:"Connexion réussie",user:t,token:i})}),router.get("/me",authenticate,(e,r)=>{const s=toUser(db.prepare("SELECT * FROM users WHERE id = ?").get(e.user.id));r.json({success:!0,user:s})}),router.put("/me",authenticate,(e,r)=>{const{name:s,surname:n,profession:o,neighborhood:t,bio:i,skills:a,avatar:u}=e.body;db.prepare("UPDATE users SET
      name = COALESCE(?, name),
      surname = COALESCE(?, surname),
      profession = COALESCE(?, profession),
      neighborhood = COALESCE(?, neighborhood),
      bio = COALESCE(?, bio),
      skills = COALESCE(?, skills),
      avatar = COALESCE(?, avatar)
    WHERE id = ?").run(s,n,o,t,i,a?JSON.stringify(a):void 0,u,e.user.id);const d=toUser(db.prepare("SELECT * FROM users WHERE id = ?").get(e.user.id));r.json({success:!0,message:"Profil mis à jour",user:d})}),module.exports=router;
